server.port=8080

# 允许跨域（前端开发服务器）
spring.websocket.allowed-origins=*

stepfun.api.key=
stepfun.asr.url=wss://api.stepfun.com/v1/realtime/asr/stream
stepfun.tts.url=wss://api.stepfun.com/v1/realtime/audio?model=step-tts-mini
stepfun.tts.voice=livelybreezy-female
stepfun.llm.url=https://api.stepfun.com/v1/chat/completions
stepfun.llm.model=step-3.5-flash-2603
# Sierra Headless API
sierra.api.token=
sierra.api.key=
sierra.api.url=https://eu.api.sierra.chat/chat
sierra.api.compatibility-date=2025-02-01
# FANO ASR
fano.asr.url=https://agent-aws-poc-hase.fano.ai/speech/recognize
fano.asr.token=
# 阿里云百炼 ASR
aliyun.asr.url=wss://dashscope.aliyuncs.com/api-ws/v1/inference
aliyun.asr.api-key=
